-- Главная таблица проекта - хранит в себе все посты в блоге
create table post (
    post_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR NOT NULL,
    picture_base_64 VARCHAR,
    content VARCHAR
)